services:
  spring:
    image: openjdk:11-jre
    volumes:
      - "../build/libs:/app"
    entrypoint: [ "java", "-jar", "/app/dhs-0.0.1-SNAPSHOT.jar" ]
    expose:
      - "8080"
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ../config/nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    ports:
      - 80:80
      - 443:443
    depends_on:
      - spring

  redis:
    image: redis:7.2.3-alpine
    expose:
      - "6379"
    volumes:
      - /data/redis:/data/redis
