services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ 'CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u root --password=$${MYSQL_ROOT_PASSWORD}' ]
      interval: 10s
      timeout: 2s
      retries: 100
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: dhs_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul

  spring:
    image: openjdk:11-jre-slim
    volumes:
      - "../build/libs:/app"
    entrypoint: [ "java", "-jar", "/app/dhs-0.0.1-SNAPSHOT.jar" ]
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql

volumes:
  mysql-data:
